version: 2

builds:
  - main: ./cmd/ccost
    binary: ccost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

homebrew_casks:
  - repository:
      owner: zulerne
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/zulerne/ccost
    description: Fast CLI to analyze Claude Code token usage and costs

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
