version: 2

builds:
  - main: ./cmd/ccost
    binary: ccost
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

brews:
  - repository:
      owner: zulerne
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/zulerne/ccost
    description: Fast CLI to analyze Claude Code token usage and costs
    license: MIT
    install: |
      bin.install "ccost"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^ci:"
      - "^test:"
  groups:
    - title: Bug Fixes
      regexp: "^fix:"
    - title: Features
      regexp: "^feat:"
    - title: Other
      regexp: ".*"
